services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mediConnectDb
      MYSQL_USER: D6_93044_Parth
      MYSQL_PASSWORD: manager
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"   # TEMPORARY      # Connected to the internal 'mysql' service name
    environment:
      DB_URL: jdbc:mysql://mysql:3306/mediConnectDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: D6_93044_Parth
      DB_PASSWORD: manager
      RAZORPAY_API_KEY: Some key
      RAZORPAY_API_SECRET: Some Secret

  frontend:
    build: ./frontend
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "5173:5173"   # TEMPORARY
    environment:
      VITE_API_URL: /api
      # PASTE YOUR NEW KEY BELOW (SAME AS BACKEND)
      VITE_RAZORPAY_KEY_ID: Some key

volumes:
  mysql_data:
