spring.application.name=backend

#DB config
#DB config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mediConnectDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:D6_93044_Parth}
spring.datasource.password=${DB_PASSWORD:manager}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#default server port 8080
#server.port=9090

razorpay.api.key=${RAZORPAY_KEY:rzp_test_SBPwwtjSFlv2x1}
razorpay.api.secret=${RAZORPAY_SECRET:hhJSxsTY0wWT20GtuBiJUgPz}


